### ISSUE TITLE
Terrain texture

### ISSUE THREAD

**Issue by fgsoftware1** [tetreum/brickcraft#6]
terrain appear as folder when import to blender

![Captura de ecrã 2022-01-16 161256](https://user-images.githubusercontent.com/60277618/149668486-10f3ad29-3abc-4eb7-bf97-edfeba94d467.png)

**Comment by tetreum** [comment]
Dunno how Blender works but it's an image s:
https://github.com/tetreum/brickcraft/blob/main/Assets/Resources/Textures/Terrain.png

**Comment by fgsoftware1** [comment]
@tetreum i figured out. Please acept my friend request on discord i need to talk with you

**Comment by fgsoftware1** [comment]
@tetreum i figured out. Please acept my friend request on discord i need to talk with you or add me 
Gabriel Aguiar#8806
